"""Configuration, Models, and Cache layer for Intelligence Agent."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

load_dotenv()

CITY_PROFILE_TTL_DAYS = 7          # How often to refresh dynamic city intelligence
NEWS_ARTICLE_LIMIT    = 8          # Max articles per API query
RSS_ITEM_LIMIT        = 10         # Max items per RSS feed
HEADLINE_DEDUP_CHARS  = 70         # Characters used for dedup key
MAX_HEADLINES_TO_LLM  = 80         # Trim before LLM to stay in context budget
LLM_MODEL             = "gpt-4o-mini"   # Change to "gpt-4o-mini" for lower cost


CITY_REGISTRY: Dict[str, Dict[str, Any]] = {
    "BHR": {
        "name"            : "Bihar",
        "state"           : "Bihar",
        "lat"             : 25.5941,
        "lon"             : 85.1376,
        "typical_peak_mw" : 7000,
        "primary_discom"  : ["NBPDCL", "SBPDCL"],
        "climate_zone"    : "Humid subtropical, extreme summer heat",
    },
    "UP": {
        "name"            : "Lucknow",
        "state"           : "Uttar Pradesh",
        "lat"             : 26.8467,
        "lon"             : 80.9462,
        "typical_peak_mw" : 28000,
        "primary_discom"  : ["UPPCL", "MVVNL", "PVVNL"],
        "climate_zone"    : "Humid subtropical, extreme summer + fog winter",
    },
    "WB": {
        "name"            : "Kolkata",
        "state"           : "West Bengal",
        "lat"             : 22.5726,
        "lon"             : 88.3639,
        "typical_peak_mw" : 9500,
        "primary_discom"  : ["CESC", "WBSEDCL"],
        "climate_zone"    : "Tropical monsoon, humid subtropical",
    },
    "KAR": {
        "name"            : "Bengaluru",
        "state"           : "Karnataka",
        "lat"             : 12.9716,
        "lon"             : 77.5946,
        "typical_peak_mw" : 16000,
        "primary_discom"  : ["BESCOM", "GESCOM"],
        "climate_zone"    : "Tropical savanna, mild summer, pleasant winters",
    },
}


RSS_FEEDS: Dict[str, str] = {
    "ToI National"       : "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    "The Hindu National" : "https://www.thehindu.com/news/national/feeder/default.rss",
    "ET Energy"          : "https://energy.economictimes.indiatimes.com/rss/topstories",
    "PIB India"          : "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=3",
    "Hindu Business"     : "https://www.thehindubusinessline.com/economy/?service=rss",
    "LiveMint Economy"   : "https://www.livemint.com/rss/economy",
    "POSOCO / Grid-India": "https://posoco.in/feed/",
    "NRLDC (North Grid)" : "https://nrldc.in/feed/",
    "WRLDC (West Grid)"  : "https://wrldc.in/feed/",
    "SRLDC (South Grid)" : "https://srldc.in/feed/",
    "ERLDC (East Grid)"  : "https://erldc.in/feed/",
}


@dataclass
class CityIntelligence:
    """
    Dynamically discovered city-specific knowledge.
    Generated by LLM from recent news; cached with a TTL.
    """
    node_id                : str
    city_name              : str
    generated_on           : str           # ISO date string

    # Discovered by LLM  NOT hardcoded
    generation_mix         : str           # e.g. "~70% coal, ~20% hydro, ~10% solar"
    primary_fuel_sources   : List[str]     # e.g. ["WCL Wardha mines", "NTPC Korba imports"]
    fuel_supply_routes     : List[str]     # e.g. ["Central Railway WCL siding", "Koradi road corridor"]
    key_vulnerabilities    : List[str]     # e.g. ["Aging Koradi unit 5 prone to forced outage"]
    seasonal_demand_factors: List[str]     # e.g. ["Cotton ginning Oct-Dec adds ~80 MW rural"]
    demand_drivers         : List[str]     # e.g. ["IT parks", "steel rolling mills", "pumping irrigation"]
    neighboring_exchange   : List[str]     # e.g. ["Imports from Chhattisgarh via PGCIL 400kV Wardha"]
    llm_confidence         : float         # 0.01.0 confidence in generated profile
    sources_used           : List[str]     # News sources that informed this profile

    def is_stale(self, ttl_days: int = CITY_PROFILE_TTL_DAYS) -> bool:
        generated = date.fromisoformat(self.generated_on)
        return (date.today() - generated).days >= ttl_days


@dataclass
class DetectedEvent:
    """A live, dynamically detected large-scale electricity-affecting event."""
    event_type       : str    # "sports", "political", "cultural", "religious", "trade", "disaster", "other"
    event_name       : str    # Free text description
    location         : str    # Venue / area
    dates            : str    # "2025-03-26 to 2025-03-28" or "2025-03-27"
    days_away        : int    # Days until event (0 = today/ongoing). HARD MAX = 7.
    duration_days    : int    # Expected duration
    grid_mechanism   : str    # "TV_PICKUP" | "HEAVY_INFRA" | "ROUTINE_DISRUPTION" | "MASS_GATHERING"
    est_attendees    : str    # e.g. "50,000100,000" or "city-wide" for TV pickup
    est_mw_impact    : str    # e.g. "+150 to +250 MW additional load"
    demand_direction : str    # "increase" | "decrease" | "mixed"
    confidence       : str    # "low" | "medium" | "high"
    source_headlines : List[str]


@dataclass
class WeatherSummary:
    current_temp_c       : float
    current_humidity_pct : int
    current_condition    : str
    week_max_c           : float
    week_max_heat_index_c: float
    week_total_rain_mm   : float
    forecast_days        : List[Dict[str, Any]]
    hourly_forecast_7d   : List[Dict[str, Any]]


@dataclass
class GridMultipliers:
    pre_event_hoard                : bool
    temperature_anomaly            : float
    economic_demand_multiplier     : float
    generation_capacity_multiplier : float
    demand_spike_risk              : str   # LOW / MEDIUM / HIGH / CRITICAL
    supply_shortfall_risk          : str
    seven_day_demand_forecast_mw_delta: int
    confidence                     : float
    key_driver                     : str
    reasoning                      : str


@dataclass
class NodeResult:
    node_id             : str
    city                : str
    generated_at        : str
    weather             : Optional[WeatherSummary]
    city_intelligence   : Optional[CityIntelligence]
    detected_events     : List[DetectedEvent]
    extracted_signals   : str
    impact_narrative    : str
    grid_multipliers    : Optional[GridMultipliers]
    phase_trace         : Optional[Dict[str, Any]] = None
    error               : Optional[str] = None


class CityIntelligenceCache:
    """
    Persists CityIntelligence objects to disk with a TTL.
    Cold boot: LLM generates fresh profile.
    Warm boot: Load from disk if < CITY_PROFILE_TTL_DAYS old.
    """

    def __init__(self, cache_dir: Path):
        self._dir = cache_dir
        self._dir.mkdir(parents=True, exist_ok=True)

    def _path(self, node_id: str) -> Path:
        return self._dir / f"city_intel_{node_id}.json"

    def load(self, node_id: str) -> Optional[CityIntelligence]:
        p = self._path(node_id)
        if not p.exists():
            return None
        try:
            data = json.loads(p.read_text())
            ci = CityIntelligence(**data)
            if ci.is_stale():
                print(f"    [CACHE] City intel for {node_id} is stale  refreshing.")
                return None
            print(f"    [CACHE] Loaded city intel for {node_id} (generated {ci.generated_on})")
            return ci
        except Exception as exc:
            print(f"    [!] Cache load failed for {node_id}: {exc}")
            return None

    def save(self, ci: CityIntelligence) -> None:
        p = self._path(ci.node_id)
        p.write_text(json.dumps(asdict(ci), indent=2))
        print(f"    [CACHE] Saved city intel for {ci.node_id}  {p}")
